create database TwoEng;
use TwoEng;
create table NguoiDung (UserID char(10), Password char(200), Firstname nvarchar(30), Lastname nvarchar(10), Email varchar(50), GioiTinh nvarchar(5), NgaySinh varchar(10), DiaChi nvarchar(100), SDT varchar(15), LoaiTK char(2), code char(6));
create table DangKi (STT int AUTO_INCREMENT primary key, HoTen nvarchar(100), SoDienThoai char(11), Email varchar(50), CMND char(10), PhuongThucDongHocPhi nvarchar(20), Lop nvarchar(50), onlineORoffline nvarchar(15), Ca varchar(10), Thu varchar(10), NgayKhaiGiang varchar(11), TinhTrang int);
create table KhaiGiang (STT int AUTO_INCREMENT primary key, MaKhoaHoc char(10), MaLop char(20), TenKhoaHoc nvarchar(50), Ca varchar(15), Thu varchar(10), Ngay varchar(15), Loai nvarchar(20), TinhTrang int);
create table Lop (MaLop char(20) primary key, TenLop nvarchar(50), MatKhau char(200), TinhTrang int);
create table BaiTapLop (STT int AUTO_INCREMENT primary key, MaLop char(20), YeuCau nvarchar(500), MoTa nvarchar(500), Filename nvarchar(50));
create table BaiNop (STT int AUTO_INCREMENT primary key, STTBai int, MaLop char(20), MaHV char(10), Filename nvarchar(50));
create table XepLop (STT int AUTO_INCREMENT primary key, MaLop char(20), MaHV char(10));
create table Sach (STT int AUTO_INCREMENT primary key, MaSach char(40), TenSach nvarchar(200), Hinh varchar(200), Gia int, MoTa nvarchar(1000));
create table GiangDay (STT int AUTO_INCREMENT primary key, MaGV char(10), MaLop char(20));
create table LichSuTest (STT int AUTO_INCREMENT primary key, UserID char(10), TenBaiTest nvarchar(100), TongSoCau int, SoCauDung int, ThoiGianTest nvarchar(30));
create table DatHang (STT int AUTO_INCREMENT primary key, MaSach char(40), TenSach nvarchar(200), DonGia nvarchar(20), SoLuong int, HoTen nvarchar(100), SoDienThoai char(20), Email varchar(100), DiaChi nvarchar(500), HinhThucThanhToan nvarchar(200), TongTienHang nvarchar(50), PhiVanChuyen nvarchar(10), ThanhTien nvarchar(50), TinhTrang int);


insert into GiangDay(MaGV, MaLop) values("GV1", "TOEIC210");
insert into GiangDay(MaGV, MaLop) values("GV1", "TOEIC410");
insert into GiangDay(MaGV, MaLop) values("GV2", "IELTS111");
insert into GiangDay(MaGV, MaLop) values("GV2", "VNU-EPT789");
insert into GiangDay(MaGV, MaLop) values("GV3", "GIAOTIEP10");

insert into Lop values("TOEIC210", "TOEIC 2 Kỹ Năng", "$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O", '0');
insert into Lop values("TOEIC410", "TOEIC 4 Kỹ Năng", "$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O", '0');
insert into Lop values("IELTS111", "Luyện Thi IELTS", "$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O", '0');
insert into Lop values("VNU-EPT789", "Luyện Thi VNU-EPT", "$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O", '0');
insert into Lop values("GIAOTIEP10", "TIếng Anh Giao Tiếp", "$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O", '0');


insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("toeic750read", "Sách - Luyện thi TOEIC 750 READING", "./img-sach/toeic750read.png", 104300 , "5 TIẾNG MỖI NGÀY, ĐẠT NGAY 750 ĐIỂM Luyện thi TOEIC 750 Reading nói riêng và bộ TOEIC của Jo Gang-Soo nói chung, có nhiều ưu điểm hơn so với những cuốn sách luyện thi TOEIC khác từng xuất bản. Thay vì đưa ra các lý thuyết dài dòng và khó tiếp thu, tác giả đưa ra cách tiếp cận câu hỏi chi tiết tùy theo từng dạng câu hỏi. Trọng tâm của cuốn sách là những ví dụ thiết thực và hệ thống bài tập đa dạng, bám sát các dạng đề thi thật. Ứng với mỗi kiểu câu hỏi nghe, tác giả đều đưa ra nhận định khái quát về kiểu câu hỏi này (chủ đề thường gặp, xu hướng câu hỏi). Sau đó là những phân tích cụ thể, kèm theo các tips và bài vận dụng thực hành. Sau mỗi chương đều có Bài tập thực hành, cuối mỗi phần đều có bài Full Test hoàn chỉnh. Phần Tips chính là phần quý giá nhất của cuốn sách. Tác giả sẽ giúp bạn nhận diện được các đáp án bẫy, đáp án sai hay bạn có thể tìm ra đáp án đúng nhất ngay khi vừa nghe câu hỏi, chỉ bằng cách tìm những dấu hiệu rất nhỏ. Đây là điều mà chỉ những người tiếp xúc với đề thi nhiều mới có thể đúc rút ra. Cuốn sách chính là người bạn đồng hành không thể thiếu trên hành trình đến với điểm số TOEIC mơ ước của bạn.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("toeic750listen", "Sách - Luyện thi TOEIC 750 LISTENING", "./img-sach/toeic750listen.jpg", 97300 , "5 TIẾNG MỖI NGÀY, ĐẠT NGAY 750 ĐIỂM CUNG CẤP ĐỀ THI VÀ CÂU MẪU PHONG PHÚ, ĐA DẠNG PHÂN TÍCH CHI TIẾT, HIỆU QUẢ CÁCH LÀM PHẦN 7 HIỆU QUẢ TỨC THÌ – TỰ TIN HOÀN THÀNH BÀI THI TOEIC 1. Dũng cảm phá bỏ quan niệm lý thuyết là cơ bản! Dù học thuộc lòng hết lý thuyết bao la, không sai một giới từ thì liệu điểm thi của bạn có thể tăng lên không? Chỉ lý thuyết thôi chắc chắn là không đủ, phải biết vận dụng lý thuyết vào thực tiễn. Để ngăn việc học lý thuyết một cách rời rạc, vô phương hướng, giáo trình này sẽ tập trung vào những lý thuyết thường xuất hiện trong đề thi TOEIC. 2. Không giải thích dài dòng! Mọi lý thuyết đều có ví dụ và đề thi mẫu! Hầu hết sách giáo trình đều đưa ra những diễn giải hết sức dài dòng. Cuốn sách này sẽ trình bày lý thuyết thông qua những câu ví dụ và đề thi mẫu thực tế. Nhờ đó, thí sinh không chỉ rút ngắn thời gian ôn luyện mà còn nâng cao năng lực vận dụng lý thuyết vào bài thi. 3. Xu hướng ra đề mới nhất! Người viết sách không chỉ chú trọng vào nội dung ôn luyện về số lượng đơn thuần mà còn nỗ lực nâng cao chất lượng ôn luyện trong từng bài học. Ngoài ra, giáo trình còn đề cập tới cả những cấu trúc, dấu hiệu dễ gây nhầm lẫn cũng như trình bày một phần riêng về phương pháp đạt điểm cao, để giúp thí sinh giảm thiểu sai sót khi làm bài. 4. Phân tích chi tiết cách làm Phần 7! Phần 7 luôn là phần khiến các thí sinh vất vả và tốn nhiều thời gian nhất. Bởi vậy, giáo trình này phân tích đầy đủ 48 câu hỏi và tổng hợp thành những phương pháp làm bài hiệu quả để các bạn có thể áp dụng ngay vào bài thi. Chỉ cần ghi nhớ những phương pháp này và luyện tập trong vòng một tháng, các bạn có thể vượt qua được phần thi khó nhằn này sớm hơn ít nhất là 5 phút. Và như các bạn đều biết, mấu chốt để đạt điểm thi TOEIC cao không nằm đâu khác mà ở chính phần này.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("600tuvungtoeic", "Fahasa - Sách Tự Học 600 Từ Vựng Toeic", "./img-sach/600tuvungtoeic.png", 45600 , "Tự học 600 từ vựng TOEIC. 600 từ vựng TOEIC thông dụng kèm ví dụ minh họa sinh động được sử dụng trong nhiều ngữ cảnh. Thiết kế nhỏ gọn, tiện dụng, học mọi lúc mọi nơi. Cải thiện đáng kể kết quả thi TOEIC. Ghi nhớ mãi mãi.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("perfectieltsvocalbulary", "Sách luyện thi - Perfect Ielts Vocabulary", "./img-sach/perfectieltsvocabulary.png", 160106 , "Perfect IELTS Vocabulary hội tụ đầy đủ các yếu tố mà một người học IELTS, đặc biệt là những người tự học đang tìm kiếm. Cuốn sách trang bị cho người học lượng từ vựng cực “khủng” với 600 trang sách, phù hợp với 4 kỹ năng trong IELTS (nghe – nói – đọc – viết). Với kết cấu đơn giản và rõ ràng, người học từ trình độ sơ cấp cũng hoàn toàn có thể làm quen và tự học. Không chỉ sử dụng như một tài liệu tham khảo, Perfect IELTS Vocabulary còn vô cùng phù hợp với bạn sắp thi IELTS, thời gian học tập không có nhiều và muốn cải thiện nhanh chóng vốn từ vựng của mình. Sách gồm các chủ điểm từ vựng chia làm 10 nhóm (Environment, Education, Culture, Art, Technology, Transportation, Health, Media, Leisure, Social Life) với hệ thống từ vựng từ cơ bản đến nâng cao. Với mỗi từ/cụm từ, sách đều trình bày kèm theo ví dụ và phần giải thích để người học làm quen với cách dùng của những từ/cụm từ đó.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("perfectieltslisten", "Sách học tiếng anh hiệu quả - Perfect Ielts Listening", "./img-sach/perfectieltslisten.png", 104300 , "Perfect IELTS Listening Dictation Vol.1. Cuốn sách bao gồm 350 đề và đoạn hội thoại về các chủ đề gần gũi, hay xuất hiện trong bài thi IELTS Listening như địa chỉ (Address), tên người (Person), tên khách sạn (Hotel), địa chỉ trang web (Website)… và được sắp xếp rõ ràng theo xu hướng ra đề 10 năm trở lại đây như điền từ (Letter), điền số (Number) và điền kết hợp cả dạng từ và số (Letter &Number). Ở đầu từng Unit, người học sẽ được định hình trước dạng bài cần làm (điền Letter hay Number), các mẹo để nghe những nội dung đó và khi kết thúc Unit, người học sẽ được cung cấp sự khác biệt giữa tiếng Anh - Anh và Anh - Mỹ về mặt phát âm cũng như cách viết. Để người học có thể kiểm tra lại bài làm, cuốn sách cũng cung cấp đáp án và những đoạn hội thoại song ngữ Anh-Việt ở cuối sách. Từ đó, sau mỗi bài luyện tập, người học có thể biết được mình còn yếu ở phần nào, lỗi sai hay mắc phải và ghi nhớ những lỗi sai đó để về sau không lặp lại nữa. File nghe của cuốn sách được truyền tải bằng giọng đọc chuẩn như bài thi thật, giúp người học không cảm thấy bỡ ngỡ khi nghe bài thi IELTS Listening thật. Vì vậy, cuốn sách Perfect IELTS Listening Dictation Vol.1 hứa hẹn sẽ đem đến trải nghiệm chân thật nhất cho các bạn, luyện thi IELTS Listening Dictation chưa bao giờ dễ đến thế! Chúng tôi mong rằng Perfect IELTS Listening Dictation Vol.1 sẽ trở thành người bạn đắc lực trên con đường thực hiện ước mơ của các bạn.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("tuvungielts", "Fahasa - Vocabulary For Ielts - Từ Vựng Luyện Thi Ielts", "./img-sach/tuvungielts.png", 118750 , "VOCABULARY FOR IELTS - Từ Vựng Luyện Thi IELTSsẽ cung cấp cho bạn đọc một cách đầy đủ về từ vựng trong kì thi IELTS. Với cuốn sách này bạn sẽ có thêm nhiều kĩ năng về cách đánh vần từ vựng, chủ động học từ vựng và cách học từ vựng IELTS .''Từ vựng Luyện Thi IELTS'' sẽ giúp bạn có được có được cách nhìn mới về cách học Tiếng Anh: Hãy dành thời gian thích hợp để học từ vựng IELTS. Học cách đánh vần khi học từ vựng IELTS. Hãy chủ động với cách học từ vựng IELTS. Hãy thụ động trong cách học từ vựng IELTS. Cách học từ vựng IELTS đúng là phải học đúng từ vựng trong doanh mục học thuật.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("toeic800", "Fahasa - Toeic 10 Phút Mỗi Ngày 800 Điểm Trong Tầm Tay", "./img-sach/toeic800.png", 136272 , "TOEIC 10 PHÚT MỖI NGÀY 800 ĐIỂM TRONG TẦM TAY. Hướng dẫn chi tiết lộ trình học + 1001 mẹo làm bài thi TOEIC theo kiểu đề thi mới. Cuốn sách bao gồm những kiến thức bám sát đề thi TOEIC dạng mới. Các bài tập về cấu trúc ngữ pháp, đọc hiểu, từ vựng được sắp xếp từ thấp tới cao, từ dễ tới khó một cách thích hợp để người học cảm thấy hứng thú khi học. ĐẶC BIỆT, những chiến thuật, mẹo làm bài thi rất quý giá được đúc kết từ kinh nghiệm luyện thi nhiều năm của tác giả cho rất nhiều học sinh đạt kết quả cao trong các kỳ thi.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("ieltsspeak", "Fahasa - Tài Liệu Luyện Thi Nói Ielts- The Ielts Speaking Topics", "./img-sach/ieltsspeak.png", 140600 , "IELTS là một kỳ thi cực kỳ quan trọng đối với những người học tiếng Anh, đây không chỉ là kỳ thi đánh giá năng lực học tiếng Anh mà còn là chiếc chìa khóa mở ra con đường học tập và làm việc cho rất nhiều người. Chính vì quan trọng như vậy nên đề thi IELTS thường khó khăn và phức tạp hơn nhiều so với những kỳ thi năng lực tiếng Anh khác, đòi hỏi người thi phải có trình độ tiếng Anh nhất định mới có thể giành được điểm cao. Trong kỳ thi IELTS, phần thi Speaking – Thi nói luôn là kỹ năng được cho là khó và gây ngần ngại cho hầu hết mọi thí sinh. Đây là phần thi chiếm nhiều thời gian chuẩn bị và dễ gây mất bình tĩnh nhất trong khi làm bài thi. Và để hỗ trợ các bạn luyện thi IELTS phần thi nói một cách hiệu quả, công ty cổ phần sách MCBooks xin trân trọng giới thiệu cuốn sách “Tài liệu luyện thi nói IELTS – Tài liệu luyện thi nói IELTS- The IELTS speaking topics with answers” của nhóm tác giả The Windy.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("tagt29chude", "Sách Tự Học 29 Chủ Đề Giao Tiếp Tiếng Anh", "./img-sach/tagt29chude.png", 79200 , "Tự Học 29 Chủ Đề Giao Tiếp Tiếng Anh Thông Dụng Nhất là cánh vững chắc và tự tin giúp các bạn bước vào cuộc sống để học tập, phát triển nghề nghiệp và quan trọng là để không bị lạc hậu trong thế giới đầy sôi động này. Các bạn đang băn khoăn không biết đâu là những chủ đề thông dụng thường được người dùng tiếng Anh sử dụng để giao tiếp. Vốn từ vựng của bạn bị hạn chế, trong giao tiếp bạn bị bí từ cũng như không thể giao tiếp linh động do vốn từ bị gò bó. Những khó khăn của bạn sẽ sớm được “dẹp bỏ” bởi cuốn sách “Tự học 29 chủ đề giao tiếp tiếng Anh thông dụng nhất”. Cuốn sách được viết bởi nhóm tác giả The Windy – nhóm tác giả với những đầu sách học tiếng Anh nổi tiếng đã giúp đỡ cho hàng triệu người Việt thành thạo tiếng Anh.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("tagt35000cau", "Fahasa - 35000 Câu Giao Tiếp Tiếng Anh", "./img-sach/tagt35000cau.png", 95000 , "35000 Câu Giao Tiếp Tiếng Anh. Cuốn sách 35000 câu giao tiếp tiếng Anh, dành cho người học trình độ sơ cấp, trung cấp. Cuốn sách được biên soạn nhằm mục đích giúp các bạn có thể tự học nghe nói và giao tiếp tự tin với người nước ngoài. Nội dung cuốn sách được chia thành từng chủ đề thông dụng hàng ngày, có phiên âm quốc tế, phiên âm tiếng Việt và kèm theo đĩa CD để các bạn có thể thực hành.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("nghenoita", "Fahasa - Tự Học Nghe Nói Tiếng Anh Căn Bản", "./img-sach/nghenoita.png", 71453 , "Tiếng Anh được coi là một chiếc cầu nối vô hình, nó giúp bạn không chỉ có cơ hội được giao tiếp với mọi người từ khắp nơi trên thế giới, mà còn có cơ hội được chinh phục kho tri thức dồi dào của nhân loại, bạn có thể tìm hiểu về cuộc sống, văn hóa, con người của nhiều nước khác nhau. Vì vậy, việc học giao tiếp tiếng Anh đang được rất nhiều người quan tâm, để đáp ứng nhu cầu đó chúng tôi xin ra mắt bạn học cuốn “Tự học nghe nói tiếng Anh căn bản”. Cuốn sách Tự học nghe nói tiếng Anh căn bản với những mẫu câu cơ bản và tình huống giao tiếp thông dụng trong cuộc sống và công việc hàng ngày. Đặc biệt, cuốn sách sẽ được học kèm theo App và được đọc theo giọng người bản xứ, giúp bạn luyện phát âm tốt hơn. Vì vậy, cuốn sách là tài liệu cần thiết cho học viên ở trình độ sơ cấp và trung cấp. Chúng tôi hy vọng cuốn sách tiếng Anh này sẽ trở thành một tài liệu học tập hữu ích cho các bạn sinh viên hoặc người đi làm đang có nhu cầu nâng cao kỹ năng giao tiếp tiếng Anh của mình.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("130luyennghe", "Fahasa - 130 Bài Luyện Nghe Tiếng Anh (Kèm CD)", "./img-sach/130luyennghe.png", 56483 , "130 Bài Luyện Nghe Tiếng Anh (Kèm CD): Nghe là một trong 4 kỹ năng quan trọng của việc học tiếng Anh, nhưng Nghe cũng chính là một trong những điểm yếu của rất nhiều bạn học tiếng Anh. “130 bài luyện nghe tiếng Anh” sẽ là bạn đồng hành thân thiết, không thể thiếu cùng bạn đọc đang muốn nâng cao kỹ năng nghe Tiếng anh trong đời sống giao tiếp hàng ngày. Cuốn sách gồm 130 bài nghe, mỗi bài mô tả 1 chủ đề liên quan đến cuộc sống thường ngày và được sắp xếp theo thứ tự từ dễ đến khó. Các chủ đề trong sách được tuyển chọn là những chủ đề thường gặp, sử dụng trong giao tiếp và tạo hứng thú cho người học.Sau sách là phần đáp án, độc giả có thể đối chiếu, so sánh, từ đó có thể tự nhận biết được khả năng và sự tiến bộ của mình tới đâu.Cuốn sách được biên soạn một cách cẩn thận, khoa học, giúp bạn đọc thực hành các bài luyện nghe dễ dàng.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("tuhoctoeic", "Sách Phương pháp tự học TOEIC", "./img-sach/tuhoctoeic.png", 79718 , "Phương Pháp Tự Học Toeic (Tái Bản 2019): Chắc hẳn nhiều ngườimuốn chinh phục chứng chỉ ngoại ngữ TOEIC, không chỉ để nâng cao khả năng ngoại ngữ mà còn mở ra nhiều cơ hội trong công việc lẫn cuộc sống. Phương pháp tự họcTOEIC là một cẩm nang thiết thực không chỉ giúp người học TOEIC có được những kinh nghiệm luyện thi cực kỳ quý báu, mà còn giúp bất cứ ai đang muốn tự học tiếng Anh. Bốn kỹ năng Nghe – Nói – Đọc – Viết đều được tác giả - người đã 8 lần đạt điểm TOEIC tối đa trình bày súc tích, đầy đủ đi kèm với các bộ công cụ tự học chắc chắn hữu ích cho người học. Để nâng cao hiệu quả đo lường theo xu thế thời đại, phiên bản cập nhật theo định dạng đề thi mới này sẽ hướng dẫn cụ thể cho bạn về những điểm thay đổi, bổ sung trong cấu trúc mới và phương pháp làm bài. Hy vọng cuốn sách là hành trang giúp bạn vượt qua kỳ thi và đừng quên rằng: “Thành quả học TOEIC có 50% là khả năng tiếp thu kiến thức và 50% còn lại là thái độ khi luyện thi. Chính thái độ sẽ là nền tảng quyết định việc bạn sẽ học thế nào, tiến bộ nhanh hay chậm.”");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("3420tuvungtoeic", "Fahasa - 3420 Từ Vựng Cần Biết Cho TOEIC", "./img-sach/3420tuvungtoeic.png", 66794 , "Quyển sách 3420 từ vựng cần thiết cho TOEIC được biên soạn đặc biệt ở dạng Anh- Anh- Việt với mục đích dành cho những ai muốn nắm vững các từ vựng thiết yếu để dự thi TOEIC. Sách có bố cục rõ ràng và nhất quán, các từ vựng được sắp xếp theo thứ tự A-Z để các bạn tiện tra cứu. Bên cạnh đó, nghĩa của những từ vựng mà bạn cần biết được giải thích chi tiết và cặn kẽ bằng cả tiếng Anh lẫn tiếng Việt. Điều đó sẽ tạo cho bạn sự thuận lợi trong việc học và nắm từ vựng. Ngoài ra, sách còn chỉ ra các hình thức khác của từ mà bạn cũng nên học qua để nắm vững cách dùng đúng từng trường hợp. Ví dụ động từ abide có các hình thức là abided, abided, abiding; danh từ ability có hình thức số nhiều là abilities; hay các từ viết tắt A.O.B, AOL, ASAP sẽ được cho hình thức viết đầy đủ lần lượt là Any other business, American online, as soon as possible. Hy vọng cuốn sách này sẽ là một tài liệu hữu ích cho bạn trong việc học tập và tham khảo các từ vựng TOEIC để tự tin bước vào kỳ thi.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("4kntoeic", "Luyện Kỹ Năng Nghe-Nói-Đọc-Viết Tiếng Anh", "./img-sach/4kntoeic.png", 81755 , "Học Tiếng Anh là một quá trình liên tục, trong đó 4 kỹ năng Nghe, Nói, Đọc và Viết là 4 kỹ năng bạn cần để giao tiếp hoặc sử dụng thành thạo bất cứ ngôn ngữ nào. Chỉ giỏi một trong những kỹ năng này sẽ không giúp bạn giao tiếp bằng tiếng Anh được. Ví dụ, bạn cần đọc tốt trước khi bạn có thể viết tốt. Bạn cũng cần nghe được trước khi bạn có thể nói được. Làm thế nào để thành thạo 4 kỹ năng Nghe, Nói, Đọc và Viết trong một thời gian ngắn? Đó luôn là câu hỏi thường trực với những bạn đang học tiếng Anh, cũng như các bạn đang có nhu cầu đi du học, du lịch hay tìm việc làm tại công ty nước ngoài. Để giúp các bạn luyện tập thành thạo 4 kỹ năng này, chúng tôi xin giới thiệu với các bạn cuốn sách “Luyện kỹ năng nghe - nói - đọc - viết tiếng Anh” Cuốn sách gồm 75 bài hội thoại với những tình huống thông dụng **** do các giáo viên bản ngữ đọc, giúp người học có cơ hội phát triển các kỹ năng nghe, nói, đọc, viết qua các tình huống thực tế. Đặc biệt giúp bạn có thể giao tiếp tiếng Anh tốt nhất trong thời gian ngắn nhất có thể.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("vnuept", "Sách - 5 Practice Tests for the VNU-EPT", "./img-sach/vnuept.png", 120000 , "Nằm trong khuôn khổ Đề án Ngoại ngữ Quốc gia Việt Nam 2020 của Bộ Giáo dục và Đào tạo, Đại học Quốc gia TP. HCM (ĐHQG-HCM) đang từng bước cải thiện việc giảng dạy, học tập và đánh giá các chương trình tiếng Anh ở các đơn vị thành viên trong vài năm trở lại đây. Riêng về mặt đánh giá, ĐHQG-HCM đã xây dựng Chứng chỉ tiếng Anh ĐHQG-HCM (English Proficiency Test – VNU-EPT) nhằm đánh giá khả năng ngôn ngữ của sinh viên dựa trên tiêu chuẩn của khung tham chiếu chung Châu Âu (CEFR). Bài thi VNU-EPT bao gồm bốn phần – Nghe, Đọc, Viết và Nói – và kéo dài khoảng ba giờ. Theo yêu cầu của thí sinh cũng như của các trường Đại học thành viên ĐHQG-HCM về tài liệu thực hành, Trung tâm khảo thí tiếng Anh ĐHQG-HCM (TTKTTA) đã biên soạn cuốn sách có tiêu đề Five Practice Tests for the VNU-EPT. Cuốn sách này nhằm cung cấp cho thí sinh một sự chuẩn bị đầy đủ hơn qua 5 bài thi mẫu với các dạng thức và nội dung câu hỏi tương tự như một bài thi VNU-EPT thật sự.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("luyenthhivnuept", "Luyện thi VNU-EPT ĐHQG TPHCM", "./img-sach/luyenthhivnuept.jpg", 150000 , "Luyện thi VNU-EPT được tổng hợp và biên soạn để hỗ trợ thí sinh dự tuyển môn tiếng Anh của kỳ thi tuyển sinh cao học đầu vào tại các trường trong khối Đại học Quốc gia TP. HCM. Cuốn sách cung cấp những kỹ năng và chiến lược cần thiết để hoàn thành tốt tất cả các bài tập của đề thi tiếng Anh. Đây sẽ là tài liệu hỗ trợ thiết thực, giúp các thí sinh tự tin hơn khi tham gia kỳ thi.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("vnuepttest", "A Complete Skill Builder for the VNU-EPT Test", "./img-sach/vnuepttest.jpg", 200000 , "Để giúp thí sinh chuẩn bị cho kỳ thi VNU-EPT, vào tháng 12/2013, Đại học Quốc gia TP. HCM đã phát hành tài liệu học tiếng Anh A Complete Skill Builder for the VNU-EPT Test. Tài liệu này nhằm giúp thí sinh ôn lại các kiến thức về ngữ pháp, làm nền tảng cho việc xây dựng một cách có hệ thống bốn kỹ năng ngôn ngữ nghe, nói, đọc, viết.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("speakwrite", "Skill for the Toeic Test - Speaking & Writing", "./img-sach/speakwrite.jpg", 180000 , "Cuốn sách này sẽ giúp bạn có một số điểm TOEIC lý tưởng qua: Bốn đề mẫu kiểm tra TOEIC hoàn chỉnh, bao gồm cả bài speaking and writing. Một hướng dẫn rõ ràng về cách thức làm bài của TOEIC speaking and writing. Các lời khuyên hữu ích về cách làm tốt bài kiểm tra. Một đĩa CD (+ bản ghi âm) cùng với mô hình chính xác các bài phát biểu và bài báo. Trả lời và giải thích cho cả bốn phần của bài kiểm tra.");
insert into Sach(MaSach, TenSach, Hinh, Gia, MoTa) values("speaking", "Cuốn Sách Tomato TOEIC Speaking Flow", "./img-sach/speaking.jpg", 175000 , "Cuốn sách được biên soạn kết hợp những kiến thức về ngữ pháp, từ vựng cũng như những cách phát âm tiếng Anh nhằm giúp cho các bạn chuẩn bị phần nói của TOEIC được tốt hơn. Với các bạn yêu thích môn tiếng Anh thì đây là tài liệu hữu ích sẽ giúp cải thiện trình độ speaking của mình. Cuốn sách bao gồm 7 phần: Recipe 1. Grammar, Recipe 2. Vocabulary, Recipe 3. Listening, Recipe 4. Pronunciation, Recipe 5. Tư duy theo kiểu Anh, Recipe 6. Fluency, Recipe 7. Goal");



insert into NguoiDung values('HV1','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Lê Thị Hồng','Ngọc','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV2','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Trần Quốc', 'Thành','18521414@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV3','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Thị', 'A','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV4','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Lê Thị', 'B','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV5','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Trần Văn', 'C','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV6','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Ngô Văn', 'D','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV7','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Đinh Thị', 'E','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV8','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Văn', 'F','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV9','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Võ Minh', 'Q','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV10','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Hồ Thị', 'L','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV11','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV12','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV13','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV14','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV15','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV16','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV17','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV18','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV19','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV20','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV21','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV22','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV23','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV24','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV25','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV26','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV27','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV28','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV29','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV30','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('HV31','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Nguyễn Ngọc Thúy', 'Vy','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','HV','');
insert into NguoiDung values('GV1','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Trần Hồng','Nghi','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','GV','');
insert into NguoiDung values('GV2','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Đỗ Thị Hương','Lan','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','GV','');
insert into NguoiDung values('GV3','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Tô Nguyễn Nhật','Quang','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','GV','');
insert into NguoiDung values('GV4','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Mai Tiến','Dũng','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','GV','');
insert into NguoiDung values('QTV','$2y$10$rptwIi/fwKae0.a0Pppn2OQAjwFFdNWMxGdzDZxVbTUR7Qi2NM51O','Đỗ Thị Hương','Lan','18521155@gm.uit.edu.vn','Nữ','25-09-2000', 'Đồng Tháp', '0123456789','GV','');



insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC2", "TOEIC210", "Luyện Thi TOEIC 2 Kĩ Năng", "7h30 - 9h", "2 4 6", "14/12/2020", "Trực Tiếp", 1);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC4", "TOEIC410", "Luyện Thi TOEIC 4 Kĩ Năng", "7h30 - 9h", "3 5 7", "15/12/2020", "Online", 1);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("IELTS", "IELTS123", "Luyện Thi IELTS", "9h30 - 11h", "2 4 6", "14/12/2020", "Trực Tiếp", 1);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("VNU-EPT", "TOEIC410","Luyện Thi VNU-EPT", "9h30 - 11h", "3 7 5", "15/12/2020", "Trực Tiếp", 1);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("GIAOTIEP", "", "Tiếng Anh Giao Tiếp", "13h30 - 15h", "2 4 6", "14/12/2020", "Online", 1);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC2", "", "Luyện Thi TOEIC 2 Kĩ Năng", "13h30 - 15h", "3 7 5", "15/12/2020", "Trực Tiếp", 1);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("IELTS", "", "Luyện Thi IELTS", "15h30 - 17h", "2 4 6", "21/12/2020", "Online", 1);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC4", "", "Luyện Thi TOEIC 4 Kĩ Năng", "15h30 - 17h", "3 7 5", "22/12/2020", "Trực Tiếp", 1);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("GIAOTIEP", "", "Tiếng Anh Giao Tiếp", "17h30 - 19h", "2 4 6", "21/12/2020", "Trực Tiếp", 1);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC2", "", "Luyện Thi TOEIC 2 Kĩ Năng", "17h30 - 19h", "3 7 5", "22/12/2020", "Trực Tiếp", 1);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("IELTS", "", "Luyện Thi IELTS", "19h30 - 21h", "2 4 6", "21/12/2020", "Online", 1);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC4", "", "Luyện Thi TOEIC 4 Kĩ Năng", "19h30 - 21h", "3 7 5", "22/12/2020", "Trực Tiếp", 1);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC4", "", "Luyện Thi TOEIC 4 Kĩ Năng", "7h30 - 9h", "2 4 6", "28/12/2020", "Trực Tiếp", 1);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC2", "", "Luyện Thi TOEIC 2 Kĩ Năng", "7h30 - 9h", "3 5 7", "29/12/2020", "Online", 1);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("IELTS", "", "Luyện Thi IELTS", "9h30 - 11h", "2 4 6", "28/12/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("VNU-EPT", "", "Luyện Thi VNU-EPT", "9h30 - 11h", "3 7 5", "29/12/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("GIAOTIEP", "", "Tiếng Anh Giao Tiếp", "13h30 - 15h", "2 4 6", "28/12/2020", "Online", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("VNU-EPT", "", "Luyện Thi VNU-EPT", "13h30 - 15h", "3 7 5", "29/12/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC4", "", "Luyện Thi TOEIC 4 Kĩ Năng", "15h30 - 17h", "2 4 6", "4/1/2020", "Online", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC2", "", "Luyện Thi TOEIC 2 Kĩ Năng", "15h30 - 17h", "3 7 5", "5/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("GIAOTIEP", "", "Tiếng Anh Giao Tiếp", "17h30 - 19h", "2 4 6", "4/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("IELTS", "", "Luyện Thi IELTS", "17h30 - 19h", "3 7 5", "5/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("VNU-EPT", "", "Luyện Thi VNU-EPT", "19h30 - 21h", "2 4 6", "4/1/2020", "Online", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("VNU-EPT", "", "Luyện Thi VNU-EPT", "19h30 - 21h", "3 7 5", "5/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC2", "", "Luyện Thi TOEIC 2 Kĩ Năng", "7h30 - 9h", "2 4 6", "6/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC4", "", "Luyện Thi TOEIC 4 Kĩ Năng", "7h30 - 9h", "3 5 7", "7/1/2020", "Online", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("IELTS", "", "Luyện Thi IELTS", "9h30 - 11h", "2 4 6", "6/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("VNU-EPT", "", "Luyện Thi VNU-EPT", "9h30 - 11h", "3 7 5", "7/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("GIAOTIEP", "", "Tiếng Anh Giao Tiếp", "13h30 - 15h", "2 4 6", "6/1/2020", "Online", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC2", "", "Luyện Thi TOEIC 2 Kĩ Năng", "13h30 - 15h", "3 7 5", "7/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("IELTS", "", "Luyện Thi IELTS", "15h30 - 17h", "2 4 6", "8/1/2020", "Online", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC4", "", "Luyện Thi TOEIC 4 Kĩ Năng", "15h30 - 17h", "3 7 5", "9/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("GIAOTIEP", "", "Tiếng Anh Giao Tiếp", "17h30 - 19h", "2 4 6", "8/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC2", "", "Luyện Thi TOEIC 2 Kĩ Năng", "17h30 - 19h", "3 7 5", "9/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("IELTS", "", "Luyện Thi IELTS", "19h30 - 21h", "2 4 6", "8/1/2020", "Online", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC4", "", "Luyện Thi TOEIC 4 Kĩ Năng", "19h30 - 21h", "3 7 5", "9/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC4", "", "Luyện Thi TOEIC 4 Kĩ Năng", "7h30 - 9h", "2 4 6", "11/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC2", "", "Luyện Thi TOEIC 2 Kĩ Năng", "7h30 - 9h", "3 5 7", "12/1/2020", "Online", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC2", "", "Luyện Thi TOEIC 2 Kĩ Năng", "7h30 - 9h", "2 4 6", "13/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC4", "", "Luyện Thi TOEIC 4 Kĩ Năng", "7h30 - 9h", "3 5 7", "14/1/2020", "Online", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("IELTS", "", "Luyện Thi IELTS", "9h30 - 11h", "2 4 6", "13/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("VNU-EPT", "", "Luyện Thi VNU-EPT", "9h30 - 11h", "3 7 5", "14/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("GIAOTIEP", "", "Tiếng Anh Giao Tiếp", "13h30 - 15h", "2 4 6", "13/1/2020", "Online", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC2", "", "Luyện Thi TOEIC 2 Kĩ Năng", "13h30 - 15h", "3 7 5", "14/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("IELTS", "", "Luyện Thi IELTS", "15h30 - 17h", "2 4 6", "13/1/2020", "Online", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC4", "", "Luyện Thi TOEIC 4 Kĩ Năng", "15h30 - 17h", "3 7 5", "14/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("GIAOTIEP", "", "Tiếng Anh Giao Tiếp", "17h30 - 19h", "2 4 6", "13/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC2", "", "Luyện Thi TOEIC 2 Kĩ Năng", "17h30 - 19h", "3 7 5", "14/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("IELTS", "", "Luyện Thi IELTS", "19h30 - 21h", "2 4 6", "13/1/2020", "Online", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC4", "", "Luyện Thi TOEIC 4 Kĩ Năng", "19h30 - 21h", "3 7 5", "14/1/2020", "Trực Tiếp", 0);
insert into KhaiGiang(MaKhoaHoc, MaLop, TenKhoaHoc, Ca, Thu, Ngay, Loai, TinhTrang) values("TOEIC4", "", "Luyện Thi TOEIC 4 Kĩ Năng", "19h30 - 21h", "3 7 5", "14/1/2020", "Online", 0);




insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV1");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV2");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV3");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV4");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV5");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV6");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV7");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV8");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV9");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV10");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV11");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV12");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV13");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV14");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV15");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV16");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV17");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV18");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV19");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV20");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV21");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV22");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV23");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV24");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV25");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV26");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV27");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV28");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV29");
insert into XepLop(MaLop, MaHV) values("TOEIC210", "HV30");



insert into BaiTapLop(MaLop, YeuCau, MoTa, Filename) values("TOEIC210", "Điền vào đáp án", "Mỗi câu 0.5 điểm", "Bai1.txt");
insert into BaiTapLop(MaLop, YeuCau, MoTa, Filename) values("TOEIC220", "Điền vào câu", "Điền hết đáp án", "");
insert into BaiTapLop(MaLop, YeuCau, MoTa, Filename) values("TOEIC410", "Điền vào câu", "Điền hết đáp án", "");
insert into BaiTapLop(MaLop, YeuCau, MoTa, Filename) values("TOEIC440", "Điền vào câu", "Điền hết đáp án", "");
insert into BaiTapLop(MaLop, YeuCau, MoTa, Filename) values("GIAOTIEP10", "Điền vào câu", "Điền hết đáp án", "");
insert into BaiTapLop(MaLop, YeuCau, MoTa, Filename) values("TOEIC210", "Chọn đáp án đúng", "Mỗi câu 1 điểm", "Bai2.txt");
insert into BaiTapLop(MaLop, YeuCau, MoTa, Filename) values("TOEIC210", "Viết đoạn văn", "Chủ đề từ chọn", "");
insert into BaiTapLop(MaLop, YeuCau, MoTa, Filename) values("TOEIC210", "Viết báo cáo giảng dạy", "Một trong những chủ đề đã học", "");
insert into BaiTapLop(MaLop, YeuCau, MoTa, Filename) values("TOEIC210", "Điền vào câu", "Làm ít nhất 10 câu", "Bai5.txt");
insert into BaiTapLop(MaLop, YeuCau, MoTa, Filename) values("TOEIC210", "Chọn đáp án đúng", "Làm tại lớp", "");
insert into BaiTapLop(MaLop, YeuCau, MoTa, Filename) values("TOEIC210", "Viết đoạn văn", "Làm trước ở nhà, lên lớp sửa", "Bai7.txt");

